/** @type {import('@nestia/sdk').INestiaConfig} */
const config = {
  input: ["src/**/*.controller.ts"],
  output: "../../packages/api/src",
  swagger: {
    output: "swagger.json",
    beautify: true,
    info: {
      title: "API Documentation",
      version: "1.0.0",
      description: "API Documentation generated by Nestia",
    },
  },
  e2e: "test/e2e",
  simulate: true,
  clone: true,
};

export default config;
