/**
 * @packageDocumentation
 * @module api.functional.articles
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import type { Resolved } from "typia";

import type { IArticle } from "../../structures/IArticle";
import type { ICreateArticle } from "../../structures/ICreateArticle";
import type { IUpdateArticle } from "../../structures/IUpdateArticle";

/**
 * 获取所有文章
 *
 * Nestia 会自动生成：
 * - Swagger 文档：GET /articles
 * - 前端 SDK：api.functional.articles.findAll()
 * - 返回类型：Promise<IArticle[]>
 * @controller ArticleController.findAll
 * @path GET /articles
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return !!connection.simulate
    ? findAll.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...findAll.METADATA,
        template: findAll.METADATA.path,
        path: findAll.path(),
      });
}
export namespace findAll {
  export type Output = IArticle[];

  export const METADATA = {
    method: "GET",
    path: "/articles",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/articles";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<IArticle[]> => typia.random<IArticle[]>(g);
  export const simulate = (connection: IConnection): Output => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * 根据 ID 获取文章
 *
 * Nestia 会自动生成：
 * - Swagger 文档：GET /articles/:id
 * - 前端 SDK：api.functional.articles.findOne(id)
 * - 返回类型：Promise<IArticle>
 * @controller ArticleController.findOne
 * @path GET /articles/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return !!connection.simulate
    ? findOne.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...findOne.METADATA,
        template: findOne.METADATA.path,
        path: findOne.path(id),
      });
}
export namespace findOne {
  export type Output = IArticle;

  export const METADATA = {
    method: "GET",
    path: "/articles/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/articles/${encodeURIComponent(id?.toString() ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<IArticle> => typia.random<IArticle>(g);
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * 创建文章
 *
 * Nestia 会自动生成：
 * - Swagger 文档：POST /articles
 * - 前端 SDK：api.functional.articles.create({ title, content, writer })
 * - 请求体类型验证：ICreateArticle
 * - 返回类型：Promise<IArticle>
 * @controller ArticleController.create
 * @path POST /articles
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Input,
): Promise<create.Output> {
  return !!connection.simulate
    ? create.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        body,
      );
}
export namespace create {
  export type Input = ICreateArticle;
  export type Output = IArticle;

  export const METADATA = {
    method: "POST",
    path: "/articles",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/articles";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<IArticle> => typia.random<IArticle>(g);
  export const simulate = (
    connection: IConnection,
    body: create.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * 更新文章
 *
 * Nestia 会自动生成：
 * - Swagger 文档：PUT /articles/:id
 * - 前端 SDK：api.functional.articles.update(id, { title, content })
 * - 请求体类型验证：IUpdateArticle
 * - 返回类型：Promise<IArticle>
 * @controller ArticleController.update
 * @path PUT /articles/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  body: update.Input,
): Promise<update.Output> {
  return !!connection.simulate
    ? update.simulate(connection, id, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(id),
        },
        body,
      );
}
export namespace update {
  export type Input = IUpdateArticle;
  export type Output = IArticle;

  export const METADATA = {
    method: "PUT",
    path: "/articles/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/articles/${encodeURIComponent(id?.toString() ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<IArticle> => typia.random<IArticle>(g);
  export const simulate = (
    connection: IConnection,
    id: string,
    body: update.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    assert.body(() => typia.assert(body));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * 删除文章
 *
 * Nestia 会自动生成：
 * - Swagger 文档：DELETE /articles/:id
 * - 前端 SDK：api.functional.articles.remove(id)
 * - 返回类型：Promise<void>
 * @controller ArticleController.remove
 * @path DELETE /articles/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  id: string,
): Promise<void> {
  return !!connection.simulate
    ? remove.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...remove.METADATA,
        template: remove.METADATA.path,
        path: remove.path(id),
      });
}
export namespace remove {
  export const METADATA = {
    method: "DELETE",
    path: "/articles/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/articles/${encodeURIComponent(id?.toString() ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): Resolved<void> =>
    typia.random<void>(g);
  export const simulate = (connection: IConnection, id: string): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
