/**
 * @packageDocumentation
 * @module api.functional.health
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import type { Resolved } from "typia";

/**
 * @controller AppController.getHealth
 * @path GET /health
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getHealth(
  connection: IConnection,
): Promise<getHealth.Output> {
  return !!connection.simulate
    ? getHealth.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getHealth.METADATA,
        template: getHealth.METADATA.path,
        path: getHealth.path(),
      });
}
export namespace getHealth {
  export type Output = {
    status: string;
    timestamp: string;
    service: string;
  };

  export const METADATA = {
    method: "GET",
    path: "/health",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/health";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<{
    status: string;
    timestamp: string;
    service: string;
  }> =>
    typia.random<{
      status: string;
      timestamp: string;
      service: string;
    }>(g);
  export const simulate = (connection: IConnection): Output => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
